name: 'Deploy Main Branch'
on:
  push:
  pull_request:
    branches: dev

jobs:
  build-psd1:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: build
        shell: pwsh
        run: ./build_scripts/build.ps1
        env: 
            build: ${{GITHUB.RUN_NUMBER}}
            path: ${{$GITHUB_WORKSPACE}}